run_name: qwen3-1.7b-dabstep-reasoning-30-fixed-reasoning-sharegpt-sft

### model
model_name_or_path: Qwen/Qwen3-1.7B
trust_remote_code: true
export_hub_model_id: BespokeLabs/qwen3-1.7b-dabstep-reasoning-30-fixed-reasoning-sharegpt-sft

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: eval-ds-dabstep-reasoning-30-fixed-reasoning-sharegpt
template: qwen3
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 32
dataloader_num_workers: 32

### output
output_dir: saves/qwen3-1.7b-dabstep-reasoning-30-fixed-reasoning-sharegpt-sft
logging_steps: 1
save_steps: 42
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
learning_rate: 1.0e-5 
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.01
weight_decay: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
push_to_hub: true

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500